### ISSUE TITLE
Callbacks do not seem to fire

### ISSUE THREAD

**Issue by HeyFood** [Shmarkus/cordova-plugin-nuance-speechkit-sample#1]
Using the example code from the [Ionic documentation](https://ionicframework.com/docs/native/speechkit/) I get no response for my success callback.

Here's my code:

```
   this.speechkit.tts(text, 'ENG-USA').then(
      (msg) => {
        console.log("Finished speaking...");
      },
      (err) => {
        console.log(err);
      }
    );
```

**Comment by Shmarkus** [comment]
Hi, so you have URL and APP_KEY defined in your config.xml? (Is your Nuance Developer subscription valid?)
If you run the command on a device, what does logcat say?

**Comment by Shmarkus** [comment]
closing as there is no additional info
